//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnTour.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contratos
    {
        public int id_ejec { get; set; }
        public string institucion { get; set; }
        public string curso { get; set; }
        public Nullable<int> cantidad { get; set; }
        public string nombre_rep { get; set; }
        public string rut_rep { get; set; }
        public string correo_rep { get; set; }
        public string seguro { get; set; }
        public string destino { get; set; }
        public Nullable<int> costo { get; set; }
    }
}
