//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnTour.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Curso
    {
        public int id_ejecutivo { get; set; }
        public string curso1 { get; set; }
        public string institucion { get; set; }
        public Nullable<int> cantidad { get; set; }
    }
}
